# Specific examples of transitions data

# 0. Import dependencies and inputs

In [1]:
%run ../../notebook_preamble_Transitions.ipy

In [2]:
# Location to store transitions data
outputs_folder = f'{useful_paths.data_dir}processed/transitions/specific_examples/'

# File name to use for the specific examples
file_name = 'Data_example'

# First batch of transitions
path_to_val_data = data_folder + 'restricted/validation/nesta_output_16Dec.csv'
batch_results = pd.read_csv(path_to_val_data)

# 1. Prepare transitions data

## 1.0 Specify transitions

### Example 1: Generate transitions

In [3]:
# Example 1: Generate a collection of transitions (e.g. all transitions from hotel porter and hotel concierge)
transitions_df = trans_utils.get_transitions(origin_ids=[732, 329], destination_ids='report')
transitions_df = transitions_df[transitions_df.is_safe_desirable].reset_index(drop=True)
transitions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   origin_id                   21 non-null     int64
 1   origin_label                21 non-null     object
 2   destination_id              21 non-null     int64
 3   destination_label           21 non-null     object
 4   similarity                  21 non-null     float64
 5   is_jobzone_ok               21 non-null     bool
 6   is_earnings_ok              21 non-null     bool
 7   is_not_high_risk            21 non-null     bool
 8   is_safer                    21 non-null     bool
 9   is_strictly_safe            21 non-null     bool
 10  job_zone_dif                21 non-null     float64
 11  earnings_ratio              21 non-null     float64
 12  risk_dif                    21 non-null     float64
 13  prop_dif                    21 non-null     float64
 14  W_skills                    21 non-null     float64
 15  W_work                      21 non-null     float64
 16  W_essential_skills          21 non-null     float64
 17  W_optional_skills           21 non-null     float64
 18  W_activities                21 non-null     float64
 19  W_work_context              21 non-null     float64
 20  sim_category                21 non-null     object
 21  is_viable                   21 non-null     bool
 22  is_desirable                21 non-null     bool
 23  is_safe_desirable           21 non-null     bool
 24  is_strictly_safe_desirable  21 non-null     bool
dtypes: bool(9), float64(11), int64(2), object(3)
memory usage: 2.9+ KB

###Â Example 2: Use the validation dataset

In [4]:
# Example 2: Add transition data using a pre-specified list of occupation pairs
validation_data = pd.read_csv(useful_paths.data_dir + 'processed/validation/Transitions_to_validate_BATCH_1.csv')
transition_pairs = [(row.origin_id, row.destination_id) for j, row in validation_data.iterrows()]
validation_data.head(5)

,origin_id,origin_label,origin_description,destination_id,destination_label,destination_description,perfectly_matched_skills,partially_matched_skills,unmatched_skills
0,29,legal guardian,Legal guardians legally assist and support min...,2867,recreational therapist,Recreational therapists offer treatment to per...,listen actively,NaN,maintain healthcare user data confidentiality;...
1,29,legal guardian,Legal guardians legally assist and support min...,1036,social counsellor,Social counsellors provide support and guidanc...,listen actively; maintain the trust of service...,encourage counselled clients to examine themse...,reflexion; perform therapy sessions; demonstra...
2,29,legal guardian,Legal guardians legally assist and support min...,2877,social pedagogue,"Social pedagogues provide care, support, and e...",apply person-centred care; support children's ...,support the positiveness of youths; adolescent...,undertake continuous professional development ...
3,29,legal guardian,Legal guardians legally assist and support min...,2654,employment and vocational integration consultant,Employment and vocational integration consulta...,give advice on personal matters; listen actively,facilitate job market access; develop course o...,observe confidentiality; communicate by teleph...
4,29,legal guardian,Legal guardians legally assist and support min...,1803,special educational needs teacher,Special educational needs teachers work with a...,disability care; assess the development of you...,assist children with special needs in educatio...,special needs learning equipment; observe stud...

In [5]:
transition_pairs[0:5]

[(29, 2867), (29, 1036), (29, 2877), (29, 2654), (29, 1803)]

In [6]:
transitions_df = trans_utils.get_transition_data(transition_pairs)

In [7]:
transitions_df.head(5)

,origin_id,origin_label,destination_id,destination_label,similarity,is_jobzone_ok,is_earnings_ok,is_not_high_risk,is_safer,is_strictly_safe,...,W_work,W_essential_skills,W_optional_skills,W_activities,W_work_context,sim_category,is_viable,is_desirable,is_safe_desirable,is_strictly_safe_desirable
0,29,legal guardian,2867,recreational therapist,0.370220,True,True,True,True,True,...,0.536452,0.203989,0.203989,0.340975,0.731929,min_viable,True,True,True,True
1,29,legal guardian,1036,social counsellor,0.364106,True,True,True,True,True,...,0.654659,0.073114,0.073994,0.513570,0.795748,min_viable,True,True,True,True
2,29,legal guardian,2877,social pedagogue,0.352374,True,True,True,False,False,...,0.579094,0.086090,0.165216,0.374458,0.783730,min_viable,True,True,True,False
3,29,legal guardian,2654,employment and vocational integration consultant,0.333975,True,True,True,True,True,...,0.549595,0.117440,0.119270,0.374365,0.724825,min_viable,True,True,True,True
4,29,legal guardian,1803,special educational needs teacher,0.319810,True,True,True,True,True,...,0.506951,0.019986,0.245352,0.305689,0.708213,min_viable,True,True,True,True

## 1.1 Table of transitions

In [8]:
# Select only the desired columns
transitions_table = transitions_df[[
    'origin_id', 'origin_label', 'destination_id', 'destination_label',
    'similarity', 'W_essential_skills', 'W_optional_skills', 'W_activities', 'W_work_context',
    'sim_category', 'is_viable', 'is_desirable', 'is_safe_desirable']]

transitions_table.sample(5)

,origin_id,origin_label,destination_id,destination_label,similarity,W_essential_skills,W_optional_skills,W_activities,W_work_context,sim_category,is_viable,is_desirable,is_safe_desirable
4213,2627,headteacher,2827,human resources manager,0.344968,0.107537,0.183114,0.325867,0.763354,min_viable,True,True,True
703,480,middle office analyst,1831,economist,0.300162,0.079616,0.204452,0.121489,0.795092,min_viable,True,True,True
3478,1945,drafter,2150,process engineer,0.397356,0.164560,0.460599,0.272954,0.691312,min_viable,True,True,True
4739,2879,child day care centre manager,2884,construction manager,0.300201,0.072876,0.158558,0.325293,0.644077,min_viable,True,True,True
3855,2203,3D modeller,1264,graphic designer,0.374883,0.067117,0.070508,0.582743,0.779163,min_viable,True,True,True

Notes: The column `similarity` stores the combined similarity measure, i.e. the average of the four different similarity measures described in the Mapping Career Causeways report. These are also provided in the columns `W_{x}`).

Column `sim_category` indicates whether the combined similarity is above 0.4 ('highly viable') or only between 0.3 and 0.4 ('minimally viable').

The columns `is_viable`, `is_desirable`, `is_safe_desirable` should be clear (see the report for more details).

### Export transitions

In [9]:
transitions_table.to_csv(f'{outputs_folder}{file_name}_Transitions.csv', index=False)

## 1.2 Table of occupational profiles

In [10]:
#Â Select all IDs involved in the transitions
all_ids = set(transitions_table.origin_id.to_list()).union(set(transitions_table.destination_id.to_list()))

In [11]:
#Â Occupational profiles
occ_profiles = data.occ_report[data.occ_report.id.isin(all_ids)]
occ_profiles.sample(5)

,id,concept_type,concept_uri,preferred_label,isco_level_1,isco_level_2,isco_level_3,isco_level_4,is_top_level,job_zone,...,onet_occupation,level_1,level_2,skills_based_sector_code,sub_sector_code,skills_based_sector,sub_sector,remote_labor_index,physical_proximity,exposure_score
578,1064,Occupation,http://data.europa.eu/esco/occupation/591c5063...,aviation data communications manager,3,35,351,3513,True,4.0,...,computer network support specialists,0,3,1,1.4,"technicians, construction, transport & securit...",transport & security workers,0.625000,0.5500,0.454148
1365,2441,Occupation,http://data.europa.eu/esco/occupation/cf2b03cd...,ICT network engineer,2,25,252,2523,True,4.0,...,computer network architects,11,46,12,12.2,ict workers,developers & testers,0.709677,0.3925,0.337567
1006,1793,Occupation,http://data.europa.eu/esco/occupation/9729c0f3...,data centre operator,3,35,351,3511,True,3.0,...,computer operators,11,47,12,12.3,ict workers,data workers,0.357143,0.4150,0.516513
130,224,Occupation,http://data.europa.eu/esco/occupation/11df8941...,sociologist,2,26,263,2632,True,5.0,...,sociologists,4,20,5,5.1,engineers & researchers,researchers & science technicians,0.700000,0.3975,0.345326
763,1376,Occupation,http://data.europa.eu/esco/occupation/731ecac4...,room attendant,9,91,911,9112,True,2.0,...,maids and housekeeping cleaners,2,11,3,3.1,sales & services workers,"food, cleaning & services workers",0.200000,0.4175,0.577927

Please select the columns, which you find are the most relevant. For more information about the column data, please see [here](https://github.com/nestauk/mapping-career-causeways/tree/main/supplementary_online_data/transitions#number-of-transition-options-for-esco-occupations).

In [12]:
occ_profiles.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 954 entries, 1 to 1625
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        954 non-null    int64
 1   concept_type              954 non-null    object
 2   concept_uri               954 non-null    object
 3   preferred_label           954 non-null    object
 4   isco_level_1              954 non-null    int64
 5   isco_level_2              954 non-null    int64
 6   isco_level_3              954 non-null    int64
 7   isco_level_4              954 non-null    int64
 8   is_top_level              954 non-null    bool
 9   job_zone                  954 non-null    float64
 10  education_level           954 non-null    float64
 11  related_work_experience   954 non-null    float64
 12  on_the_job_training       954 non-null    float64
 13  annual_earnings           954 non-null    float64
 14  total_paid_hours          954 non-null    float64
 15  employment_count          933 non-null    float64
 16  employment_share          933 non-null    float64
 17  risk                      954 non-null    float64
 18  prevalence                954 non-null    float64
 19  risk_category             954 non-null    object
 20  onet_code                 954 non-null    object
 21  onet_occupation           954 non-null    object
 22  level_1                   954 non-null    int64
 23  level_2                   954 non-null    int64
 24  skills_based_sector_code  954 non-null    int64
 25  sub_sector_code           954 non-null    float64
 26  skills_based_sector       954 non-null    object
 27  sub_sector                954 non-null    object
 28  remote_labor_index        935 non-null    float64
 29  physical_proximity        954 non-null    float64
 30  exposure_score            935 non-null    float64
dtypes: bool(1), float64(14), int64(8), object(8)
memory usage: 232.0+ KB

### Export profiles

In [13]:
occ_profiles.to_csv(f'{outputs_folder}{file_name}_Occupation_profiles.csv', index=False)

## 1.3 Skills matching data for specific transitions

In [14]:
# Choose a row of the transition table
row = 0

# Get skills matches
skills_matching = trans_utils.show_skills_overlap(transitions_table.loc[row].origin_id,
                                                  transitions_table.loc[row].destination_id,
                                                  skills_match='optional',
                                                  verbose=True)

# Export the skills matching table
skills_matching.to_csv(f'{outputs_folder}{file_name}_Skills_match_{row}.csv', index=False)

skills_matching

from legal guardian (id 29) to recreational therapist (id 2867)
--------
5/5 destination skills matched
NLP-adjusted overlap = 0.20 (total combined similarity: 0.37)

,origin_skill_id,origin_skill,destination_skill_id,destination_skill,similarity,score
0,8560,listen actively,8560,listen actively,1.000000,0.998
1,6511,apply person-centred care,11438,develop a collaborative therapeutic relationship,0.793362,0.021
2,1534,provide first aid,9236,assess the patient's therapeutic needs,0.692435,0.000
3,4350,personal development,5159,provide health education,0.684532,0.000
4,12484,maintain the trust of service users,4363,maintain healthcare user data confidentiality,0.597850,0.000

In [15]:
# Extra: You may also want to get some reference data on the skills (links to the ESCO database)
all_skills_ids = set(skills_matching.origin_skill_id.to_list()).union(set(skills_matching.destination_skill_id.to_list()))
data.skills[data.skills.id.isin(all_skills_ids)]

,concept_type,concept_uri,skill_type,reuse_level,preferred_label,alt_labels,description,id,code,skill_category,level_1,level_2,level_3,level_title,level_href,level_uri
1534,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/1d21f6ad-340f...,skill/competence,cross-sector,provide first aid,administer cardiopulmonary resuscitation\nexec...,Administer cardiopulmonary resuscitation or fi...,1534,S3.2.1,S,S3,S3.2,S3.2.1,"providing medical, dental and nursing care",https://ec.europa.eu/esco/api/resource/concept...,http://data.europa.eu/esco/skill/S3.2.1
4350,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/519e801b-3cc4...,knowledge,cross-sector,personal development,self-reflection\ntechniques and methods for pe...,The techniques and methods used to improve awa...,4350,K0.3.0,K,K0,K0.3,K0.3.0,personal skills and development,https://ec.europa.eu/esco/api/resource/concept...,http://data.europa.eu/esco/isced-f/0031
4363,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/51ece34f-c24e...,skill/competence,sector-specific,maintain healthcare user data confidentiality,comply with confidentiality of healthcare user...,Comply with and maintain the confidentiality o...,4363,S3.3.6,S,S3,S3.3,S3.3.6,protecting privacy and personal data,https://ec.europa.eu/esco/api/resource/concept...,http://data.europa.eu/esco/skill/S3.3.6
5159,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/60b2dd49-c677...,skill/competence,cross-sector,provide health education,advocate for health\nprovide a health educatio...,Provide evidence based strategies to promote h...,5159,S1.3.4,S,S1,S1.3,S1.3.4,training on health or medical topics,https://ec.europa.eu/esco/api/resource/concept...,http://data.europa.eu/esco/skill/S1.3.4
6511,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/7a63f944-6948...,skill/competence,sector-specific,apply person-centred care,apply patient-focused care\nemploy person-cent...,"Treat individuals as partners in planning, dev...",6511,S3.6.2,S,S3,S3.6,S3.6.2,assisting with personal needs,https://ec.europa.eu/esco/api/resource/concept...,http://data.europa.eu/esco/skill/S3.6.2
8560,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/a17286c5-238d...,skill/competence,cross-sector,listen actively,maintain active listening\napply active listen...,"Give attention to what other people say, patie...",8560,S1.7.3,S,S1,S1.7,S1.7.3,listening and asking questions,https://ec.europa.eu/esco/api/resource/concept...,http://data.europa.eu/esco/skill/S1.7.3
9236,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/ae8f9a47-aff5...,skill/competence,sector-specific,assess the patient's therapeutic needs,assess patients' therapeutic needs\nevaluate t...,"Observe and assess the patient`s behaviour, at...",9236,S2.1.2,S,S2,S2.1,S2.1.2,diagnosing health conditions,https://ec.europa.eu/esco/api/resource/concept...,http://data.europa.eu/esco/skill/S2.1.2
11438,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/d93f9e29-9740...,skill/competence,cross-sector,develop a collaborative therapeutic relationship,develop collaborative therapeutic relationship...,Develop a mutually collaborative therapeutic r...,11438,S1.2.3,S,S1,S1.2,S1.2.3,developing professional relationships or networks,https://ec.europa.eu/esco/api/resource/concept...,http://data.europa.eu/esco/skill/S1.2.3
12484,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/edf5a26c-8a71...,skill/competence,cross-sector,maintain the trust of service users,establish trust and confidence of the patient\...,Establish and maintain the trust and confidenc...,12484,S1.2.3,S,S1,S1.2,S1.2.3,developing professional relationships or networks,https://ec.europa.eu/esco/api/resource/concept...,http://data.europa.eu/esco/skill/S1.2.3

## 2. Data Sample export

In [18]:
transition_mean = batch_results.groupby('subject_ids')['feasibility_1-5'].mean()
transitions = batch_results.reset_index().drop_duplicates('subject_ids').set_index('subject_ids')

export_jobs = ['user interface developer', 'lottery cashier', 
               'community health worker', 'sales support assistant', 
               'travel agent', 'postman/postwoman', 'real estate surveyor',
               'investment clerk', 'financial analyst', 'packaging production manager'
              ]

sample_transitions = (transitions
                      .reset_index()
                      .set_index('origin_label')
                      .loc[export_jobs]
                      .reset_index()
                      .set_index('subject_ids'))

In [19]:
sample_transitions = sample_transitions.merge(transition_mean, left_index=True, 
                                              right_index=True, how='inner', 
                                              suffixes=('_raw', '_mean')
                                             )

sample_transitions = sample_transitions[sample_transitions['feasibility_1-5_mean'] > 2]

In [20]:
with open(data_folder + 'restricted/validation/data_sample_ids.txt', 'w') as f:
    for l in [str(tuple(r)) for r in sample_transitions[['origin_id', 'destination_id']].to_numpy()]:
        f.write(l + '\n')

In [21]:
from ast import literal_eval

In [22]:
with open(data_folder + 'restricted/validation/data_sample_ids.txt', 'r') as f:
    sample_ids = f.read().splitlines()
    
sample_ids = [literal_eval(l) for l in sample_ids]

### 2.1 Sample Transitions

In [23]:
sample_transitions_df = trans_utils.get_transition_data(sample_ids)

In [24]:
sample_transitions_df = sample_transitions_df.reset_index().rename(columns={'index': 'transition_id'})

In [33]:
sample_transitions_df

,transition_id,origin_id,origin_label,destination_id,destination_label,similarity,is_jobzone_ok,is_earnings_ok,is_not_high_risk,is_safer,...,W_work,W_essential_skills,W_optional_skills,W_activities,W_work_context,sim_category,is_viable,is_desirable,is_safe_desirable,is_strictly_safe_desirable
0,0,1608,user interface developer,2786,software developer,0.527560,True,True,True,False,...,0.617730,0.291359,0.583422,0.416246,0.819213,highly_viable,True,True,True,False
1,1,1608,user interface developer,2517,digital games designer,0.432285,True,True,True,True,...,0.685992,0.148100,0.209055,0.580184,0.791800,highly_viable,True,True,True,True
2,2,1608,user interface developer,67,software analyst,0.405617,True,True,True,True,...,0.614435,0.172401,0.221198,0.401973,0.826897,highly_viable,True,True,True,True
3,3,1608,user interface developer,1318,numerical tool and process control programmer,0.342705,True,True,True,True,...,0.272596,0.075623,0.750005,0.071745,0.473447,min_viable,True,True,True,True
4,4,1608,user interface developer,261,data warehouse designer,0.339140,True,True,True,False,...,0.582882,0.064940,0.125854,0.318572,0.847193,min_viable,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,102,1705,packaging production manager,702,trade regional manager,0.323499,True,True,True,True,...,0.476750,0.151257,0.189239,0.322340,0.631159,min_viable,True,True,True,True
103,103,1705,packaging production manager,563,sales account manager,0.312026,True,True,True,True,...,0.497077,0.126865,0.127084,0.362995,0.631159,min_viable,True,True,True,True
104,104,1705,packaging production manager,2386,programme manager,0.301149,True,True,True,False,...,0.507389,0.093333,0.096484,0.221241,0.793537,min_viable,True,True,True,False
105,105,1705,packaging production manager,524,health and safety inspector,0.348616,True,True,True,True,...,0.464261,0.185493,0.280448,0.172512,0.756010,min_viable,True,True,True,True
106,106,1705,packaging production manager,1199,manufacturing manager,0.316993,True,True,True,False,...,0.466569,0.165649,0.169187,0.112874,0.820263,min_viable,True,True,True,False

### 2.2 Sample Job Profiles

In [25]:
#Â Select all IDs involved in the transitions
all_ids = set(sample_transitions_df.origin_id.to_list()).union(set(sample_transitions_df.destination_id.to_list()))

In [26]:
#Â Occupational profiles
sample_occ_profiles = data.occ_report[data.occ_report.id.isin(all_ids)]
sample_occ_profiles.sample(5)

,id,concept_type,concept_uri,preferred_label,isco_level_1,isco_level_2,isco_level_3,isco_level_4,is_top_level,job_zone,...,onet_occupation,level_1,level_2,skills_based_sector_code,sub_sector_code,skills_based_sector,sub_sector,remote_labor_index,physical_proximity,exposure_score
473,853,Occupation,http://data.europa.eu/esco/occupation/4887c8a5...,hospitality entertainment manager,3,33,333,3339,True,4.0,...,"agents and business managers of artists, perfo...",1,6,2,2.1,business & administration workers,"process managers, supervisors & coordinators",0.538462,0.4300,0.445490
296,524,Occupation,http://data.europa.eu/esco/occupation/2b31f745...,health and safety inspector,3,33,335,3359,True,4.0,...,occupational health and safety specialists,0,0,1,1.1,"technicians, construction, transport & securit...",engineering technicians,0.500000,0.6475,0.568990
164,294,Occupation,http://data.europa.eu/esco/occupation/18552245...,"gambling, betting, and lottery game developer",2,21,212,2120,True,4.0,...,video game designers,11,46,12,12.2,ict workers,developers & testers,0.735849,0.5125,0.367937
1223,2186,Occupation,http://data.europa.eu/esco/occupation/b915ab4a...,property acquisitions manager,3,33,333,3334,True,4.0,...,"property, real estate, and community associati...",1,7,2,2.2,business & administration workers,accounting & financial services workers,0.631579,0.5100,0.433468
58,106,Occupation,http://data.europa.eu/esco/occupation/07e60525...,integration engineer,2,25,251,2511,True,4.0,...,computer systems analysts,11,45,12,12.1,ict workers,"ict system engineers, adminstrators & managers",0.777778,0.4775,0.325747

### 2.3 Sample Skills

In [29]:
rows = sample_transitions_df[['transition_id', 'origin_id', 'destination_id']].iterrows()

skills_matches = []

for _, (i, origin_id, destination_id) in rows:
    skills_matching = trans_utils.show_skills_overlap(origin_id, destination_id, 
                                                      skills_match='optional', verbose=False)
    skills_matching['transition_id'] = i
    skills_matches.append(skills_matching)
    
skills_matches = pd.concat(skills_matches, axis=0)

In [30]:
skills_matches.head()

,origin_skill_id,origin_skill,destination_skill_id,destination_skill,similarity,score,transition_id
0,8359,tools for software configuration management,8359,tools for software configuration management,1.0,0.998,0
1,2343,use software design patterns,2343,use software design patterns,1.0,0.998,0
2,6473,develop software prototype,6473,develop software prototype,1.0,0.998,0
3,1954,debug software,1954,debug software,1.0,0.998,0
4,1778,computer programming,1778,computer programming,1.0,0.998,0

In [31]:
# Extra: You may also want to get some reference data on the skills (links to the ESCO database)
sample_skills_ids = (set(skills_matches.origin_skill_id.to_list())
                     .union(set(skills_matches.destination_skill_id.to_list())))

sample_skill_profiles = data.skills[data.skills.id.isin(sample_skills_ids)]

In [32]:
sample_skill_profiles.head()

,concept_type,concept_uri,skill_type,reuse_level,preferred_label,alt_labels,description,id,code,skill_category,level_1,level_2,level_3,level_title,level_href,level_uri
2,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/000709ed-2be5...,skill/competence,sector-specific,apply anti-oppressive practices,apply non-oppressive practices\napply an anti-...,"Identify oppression in societies, economies, c...",2,S3.3.0,S,S3,S3.3,S3.3.0,protecting and enforcing,https://ec.europa.eu/esco/api/resource/concept...,http://data.europa.eu/esco/skill/S3.3.0
7,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/000f1d3d-220f...,knowledge,sector-specific,Haskell,NaN,The techniques and principles of software deve...,7,K6.0.3,K,K6,K6.0,K6.0.3,software and applications development and anal...,https://ec.europa.eu/esco/api/resource/concept...,http://data.europa.eu/esco/isced-f/0613
31,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/00e53a0a-c0ba...,skill/competence,sector-specific,guarantee customer satisfaction,to guarantee customer satisfaction\nensure cus...,Handle customer expectations in a professional...,31,A1.12.3,A,A1,A1.12,A1.12.3,provide high quality client service,https://ec.europa.eu/esco/api/resource/concept...,http://data.europa.eu/esco/skill/A1.12.3
58,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/016cee6c-9e95...,skill/competence,sector-specific,assess railway operations,appraise railway operations\nevaluate railway ...,"Review and study existing railroad equipment, ...",58,S2.1.1,S,S2,S2.1,S2.1.1,conducting investigations,https://ec.europa.eu/esco/api/resource/concept...,http://data.europa.eu/esco/skill/S2.1.1
70,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/01c03003-516d...,skill/competence,cross-sector,advise on construction materials,giving of advice on construction materials\ngi...,Provide advice on and test a wide range of con...,70,S1.5.3,S,S1,S1.5,S1.5.3,advising on products and services,https://ec.europa.eu/esco/api/resource/concept...,http://data.europa.eu/esco/skill/S1.5.3